import Foundation

enum DugnadRepository {
    static let filterCities = [
        "Oslo",
        "Bergen",
        "Trondheim",
        "Stavanger",
        "Fredrikstad",
        "Tromsø",
        "Bodø",
    ]

    static let sampleItems: [DugnadItem] = [
        DugnadItem(
            id: UUID(uuidString: "A1B2C3D4-E5F6-7890-ABCD-EF1234567890")!,
            title: "Vårrydding på idrettsanlegget",
            date: "Lørdag 12. april 2026, kl. 10:00",
            location: "Gressvik idrettsplass, Fredrikstad",
            city: "Fredrikstad",
            municipality: "Fredrikstad",
            region: "Viken",
            latitude: 59.2181,
            longitude: 10.9298,
            workType: "Rydde, klippe gress og male garderobe",
            description: "Vi trenger hjelp til å gjøre idrettsanlegget klart for sommersesongen. Ta med hansker og arbeidsklær – verktøy deles ut på stedet.",
            foodService: "Kaffe og sveler"
        ),
        DugnadItem(
            id: UUID(uuidString: "B2C3D4E5-F6A7-8901-BCDE-F12345678901")!,
            title: "Kakebaking til 17. mai-feiring",
            date: "Søndag 4. mai 2026, kl. 14:00",
            location: "Skolekjøkkenet, Risvollan skole, Trondheim",
            city: "Trondheim",
            municipality: "Trondheim",
            region: "Trøndelag",
            latitude: 63.4305,
            longitude: 10.3951,
            workType: "Bake kaker og pynte til nasjonaldagen",
            description: "Sammen baker vi kaker til 17. mai-feiringen i nabolaget. Ingen erfaring nødvendig – oppskrifter og pyntemateriell stilles til disposisjon.",
            foodService: "Te, juice og kakebit til alle frivillige"
        ),
        DugnadItem(
            id: UUID(uuidString: "C3D4E5F6-A7B8-9012-CDEF-123456789012")!,
            title: "Dugnad på fotballbanen",
            date: "Onsdag 21. mai 2026, kl. 17:30",
            location: "Viking Stadion, Stavanger",
            city: "Stavanger",
            municipality: "Stavanger",
            region: "Rogaland",
            latitude: 58.9700,
            longitude: 5.7331,
            workType: "Linjerebane, fylle sand og vedlikeholde mål",
            description: "Fotballbanen trenger vedlikehold før sommerens kamper. Vi markerer linjer, fyller på med sand og sjekker at målene er i god stand.",
            foodService: "Pølser i brød og brus"
        ),
        DugnadItem(
            id: UUID(uuidString: "D4E5F6A7-B8C9-0123-DEF0-234567890123")!,
            title: "Planting av blomsterbed i nabolaget",
            date: "Lørdag 7. juni 2026, kl. 09:00",
            location: "Fellesareal ved Bølerveien 42, Oslo",
            city: "Oslo",
            municipality: "Oslo",
            region: "Oslo",
            latitude: 59.9139,
            longitude: 10.7522,
            workType: "Grave, plante og vanne blomsterbed",
            description: "La oss gjøre nabolaget finere sammen! Vi planter blomster langs fellesarealet og rydder opp i bedene etter vinteren.",
            foodService: "Frukt, vann og vafler"
        ),
        DugnadItem(
            id: UUID(uuidString: "E5F6A7B8-C9D0-1234-EF01-345678901234")!,
            title: "Strandrydding ved Puddefjorden",
            date: "Lørdag 19. april 2026, kl. 11:00",
            location: "Puddefjorden, Bergen",
            city: "Bergen",
            municipality: "Bergen",
            region: "Vestland",
            latitude: 60.3913,
            longitude: 5.3221,
            workType: "Samle søppel og rydde langs strandlinjen",
            description: "Bergen trenger frivillige til vårrydding ved sjøen. Husk praktiske klær og vern – sekker og hansker deles ut ved oppmøte.",
            foodService: "Kaffe og skillingsboller"
        ),
        DugnadItem(
            id: UUID(uuidString: "F6A7B8C9-D0E1-2345-F012-456789012345")!,
            title: "Midnattsol-festival forberedelser",
            date: "Fredag 13. juni 2026, kl. 16:00",
            location: "Storgata scene, Tromsø",
            city: "Tromsø",
            municipality: "Tromsø",
            region: "Troms og Finnmark",
            latitude: 69.6492,
            longitude: 18.9553,
            workType: "Rigge scene, henge opp dekorasjoner og sette opp stoler",
            description: "Hjelp oss gjøre Tromsø klar for midnattsol-feiringen! Vi trenger folk til oppsetting av scene og dekorasjoner i sentrum.",
            foodService: "Reindeer wrap og varm kakao"
        ),
        DugnadItem(
            id: UUID(uuidString: "A7B8C9D0-E1F2-3456-0123-567890123456")!,
            title: "Kystrydding ved havna",
            date: "Lørdag 24. mai 2026, kl. 10:30",
            location: "Bodø havn, Bodø",
            city: "Bodø",
            municipality: "Bodø",
            region: "Nordland",
            latitude: 67.2804,
            longitude: 14.4049,
            workType: "Rydde brygge, samle avfall og vaske benker",
            description: "La oss ta vare på kysten i Bodø! Vi møtes ved havna og rydder langs bryggen og området rundt.",
            foodService: "Vaffel og kaffe"
        ),
        DugnadItem(
            id: UUID(uuidString: "B8C9D0E1-F2A3-4567-1234-678901234567")!,
            title: "Grilldugnad i Frognerparken",
            date: "Søndag 18. mai 2026, kl. 12:00",
            location: "Frognerparken, Oslo",
            city: "Oslo",
            municipality: "Oslo",
            region: "Oslo",
            latitude: 59.9200,
            longitude: 10.7000,
            workType: "Sette opp grill, rydde område og dekorere",
            description: "Felles grillfest for nabolaget i Frognerparken. Vi trenger hjelp til oppsett, rydding og pynting før gjestene ankommer.",
            foodService: "Grillmat og brus"
        ),
        DugnadItem(
            id: UUID(uuidString: "C9D0E1F2-A3B4-5678-2345-789012345678")!,
            title: "Bryggevedlikehold i Glomfjord",
            date: "Lørdag 3. mai 2026, kl. 09:30",
            location: "Glomfjord havneområde, Meløy",
            city: "Meløy",
            municipality: "Meløy",
            region: "Nordland",
            latitude: 66.8219,
            longitude: 13.3489,
            workType: "Reparere brygge, smøre utstyr og rydde kaianlegg",
            description: "Lokal dugnad for kystsamfunnet i Meløy. Vi trenger frivillige til vedlikehold av brygge og kaianlegg i Glomfjord.",
            foodService: "Fiskesuppe og flatbrød"
        ),
        DugnadItem(
            id: UUID(uuidString: "D0E1F2A3-B4C5-6789-3456-890123456789")!,
            title: "Redningsstasjon forberedelser på Røst",
            date: "Torsdag 15. mai 2026, kl. 18:00",
            location: "Røst kommunehus, Røst",
            city: "Røst",
            municipality: "Røst",
            region: "Nordland",
            latitude: 67.5175,
            longitude: 12.0946,
            workType: "Klargjøre utstyr, sjekke båter og pakke forsyninger",
            description: "Frivillig innsats for øysamfunnet på Røst. Vi klargjør utstyr og forsyninger til sesongen for kystredning.",
            foodService: "Kaffe, te og tørrfisk"
        ),
        DugnadItem(
            id: UUID(uuidString: "E1F2A3B4-C5D6-7890-4567-901234567890")!,
            title: "Setervei-rydding ved Hardangervidda",
            date: "Lørdag 31. mai 2026, kl. 08:00",
            location: "Geilo fjellstue, Geilo",
            city: "Geilo",
            municipality: "Hol",
            region: "Innlandet",
            latitude: 60.5333,
            longitude: 8.2167,
            workType: "Merke stier, rydde steinras og reparere grind",
            description: "Dugnad langs seterveier i høyfjellet. Ta med gode fjellstøvler og klær for skiftende vær.",
            foodService: "Vafler og varm saft"
        ),
        DugnadItem(
            id: UUID(uuidString: "F2A3B4C5-D6E7-8901-5678-012345678901")!,
            title: "Samisk kulturhus vedlikehold",
            date: "Lørdag 10. mai 2026, kl. 11:00",
            location: "Karasjok sentrum, Karasjok",
            city: "Karasjok",
            municipality: "Karasjok",
            region: "Troms og Finnmark",
            latitude: 69.4719,
            longitude: 25.5112,
            workType: "Male, rydde og klargjøre lokaler til kulturevent",
            description: "Vi samler frivillige for å klargjøre kulturhuset i Karasjok til vårens arrangementer i Finnmark.",
            foodService: "Reinsdyrstek og kaffe"
        ),
        DugnadItem(
            id: UUID(uuidString: "A3B4C5D6-E7F8-9012-6789-123456789012")!,
            title: "Båtnaust-reparasjon i Sømna",
            date: "Onsdag 28. mai 2026, kl. 17:00",
            location: "Sømna kirkevik, Sømna",
            city: "Sømna",
            municipality: "Sømna",
            region: "Nordland",
            latitude: 65.2589,
            longitude: 12.0344,
            workType: "Reparere båtnaust, bytte bord og behandle treverk",
            description: "Liten kystkommune med stor dugnadsånd! Vi trenger hjelp til å vedlikeholde båtnaust langs Sømna.",
            foodService: "Kaffe og hjemmebakst"
        ),
        DugnadItem(
            id: UUID(uuidString: "B4C5D6E7-F8A9-0123-7890-234567890123")!,
            title: "Bergstue-oppussing på Røros",
            date: "Søndag 1. juni 2026, kl. 10:00",
            location: "Bergstaden, Røros",
            city: "Røros",
            municipality: "Røros",
            region: "Trøndelag",
            latitude: 62.5748,
            longitude: 11.3844,
            workType: "Restaurere trepanel, rydde og male",
            description: "Historisk dugnad i Bergstaden på Røros. Vi tar vare på felles bygningsmasse i den lille fjellkommunen.",
            foodService: "Røroskake og kaffe"
        ),
        DugnadItem(
            id: UUID(uuidString: "C5D6E7F8-A9B0-1234-8901-345678901234")!,
            title: "Lofoten fiskerihavn vårklargjøring",
            date: "Fredag 23. mai 2026, kl. 15:00",
            location: "Leknes havn, Vestvågøy",
            city: "Leknes",
            municipality: "Vestvågøy",
            region: "Nordland",
            latitude: 68.1475,
            longitude: 13.6115,
            workType: "Rydde kaier, smøre vinsjer og sjekke sikkerhetsutstyr",
            description: "Sesongforberedelser i Lofoten. Frivillige hjelper fiskerihavnen med vårklargjøring før sommeren.",
            foodService: "Fiskesuppe og brød"
        ),
    ]
}
